[project]
name = "socrates"
version = "0.0.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.3",
    "orjson>=3.11.7",
    "python-dotenv>=1.2.1",
    "python-telegram-bot[rate-limiter]>=22.6",
    "requests>=2.32.5",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver2"
version_provider = "uv"
update_changelog_on_bump = false
